version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "frontend/package.json" }}
      - run:
          name: install dependencies
          command: |
            cd frontend
            yarn install
      - save_cache:
          paths:
            - frontend/node_modules
          key: v1-dependencies-{{ checksum "frontend/package.json" }}
      - run:
          name: unit test frontend
          command: |
            cd frontend
            yarn test:unit
      - run:
          name: analyze code
          command: |
            cd frontend
            sonar-scanner \
              -Dsonar.projectKey=frontends \
              -Dsonar.organization=today-eats \
              -Dsonar.sources=. \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=${frontend_token} \
              -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info
